# Generated by Django 2.1.2 on 2018-10-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_table', '0003_auto_20181012_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant1',
            name='name2',
            field=models.CharField(blank=True, db_column='name', max_length=30),
        ),
        migrations.AlterField(
            model_name='place1',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
